name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/jekyll -v ${{ github.workspace }}/_site:/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /jekyll && jekyll build --future"
