# In your repository's `.github/workflows/publish-for-netlify.yml` file.
---
# Name of your GitHub Actions workflow.
name: Publish for Netlify

# Specifies to run this workflow whenever the tag v1.2.0 is pushed
on:
  push:
    tags:
      - 'v1.2.0'

# Define a job named `build-and-publish` in your workflow.
jobs:
  build-and-publish-for-netlify:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source with the specific tag.
      - uses: actions/checkout@v3

      # Set up Ruby for Jekyll.
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      # Install Jekyll and Bundler.
      - name: Install dependencies
        run: |
          cd jekyll
          gem install bundler
          bundle install

      # Build the Jekyll site with the baseurl set to ''.
      - name: Build site for Netlify
        run: |
          cd jekyll
          JEKYLL_ENV=production bundle exec jekyll build --baseurl ""

      # Deploy to the `netlify` branch.
      - name: Deploy to 'netlify' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./jekyll/_site
          publish_branch: netlify

      # Send a webhook upon completion.
      - name: Send webhook notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Published to the 'netlify' branch successfully!"}' ${{ secrets.WEBHOOK_URL }}
