# In your repository's `.github/workflows/publish-to-github-pages.yml` file.
---
# Name of your GitHub Actions workflow.
name: Publish to GitHub Pages

# Specifies to run this workflow whenever a push is made (commits are
# added) to the branch named `main`.
on:
  push:
    branches:
      - dev

# Define a job named `build-and-publish` in your workflow.
jobs:
  build-and-publish-to-github-pages:
    runs-on: ubuntu-latest # This job uses a GitHub-hosted runner.

    steps:
      # Checkout the source from the `main` branch.
      - uses: actions/checkout@v3

      # Set up Ruby for Jekyll.
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      # Install Jekyll and Bundler.
      - name: Install dependencies
        run: |
          cd jekyll
          gem install bundler
          bundle install

      # Build the Jekyll site with the baseurl set to '/wallace-thrasher'.
      - name: Build site for GitHub Pages
        run: |
          cd jekyll
          JEKYLL_ENV=development bundle exec jekyll build --baseurl "/wallace-thrasher"

      # Copy the .github/workflows folder to the build output directory.
      - name: Copy workflows folder
        run: |
          mkdir -p jekyll/_site/.github
          cp -r .github/workflows jekyll/_site/.github/

      # Deploy to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./jekyll/_site
          keep_files: false

          # Send a webhook upon completion.
      - name: Send webhook notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Published to GitHub Pages successfully!"}' ${{ secrets.WEBHOOK_URL }}
