# In your repository's `.github/workflows/publish-for-netlify.yml` file.
---
# Name of your GitHub Actions workflow.
name: Publish for Netlify

# Specifies to run this workflow whenever code is pushed to main branch
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to publish'
        required: true
        default: 'v1.3.0'

# Define a job named `build-and-publish` in your workflow.
jobs:
  build-and-publish-for-netlify:
    runs-on: ubuntu-latest

    steps:
      # Checkout the specific version tag when triggered by push to main
      # or use the specified tag when manually triggered
      - name: Checkout specific tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag || 'v1.3.0' }}

      # Set up Ruby for Jekyll.
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      # Install Jekyll and Bundler.
      - name: Install dependencies
        run: |
          cd jekyll
          gem install bundler
          bundle install

      # Build the Jekyll site with the baseurl set to ''.
      - name: Build site for Netlify
        run: |
          cd jekyll
          JEKYLL_ENV=production bundle exec jekyll build --baseurl ""

      # Deploy to the `netlify` branch.
      - name: Deploy to 'netlify' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./jekyll/_site
          publish_branch: netlify

      # Send a webhook upon completion.
      - name: Send webhook notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Published to the 'netlify' branch successfully!"}' ${{ secrets.WEBHOOK_URL }}
