# In your repository's `.github/workflows/publish-to-github-pages.yaml` file.
---
# Name of your GitHub Actions workflow.
name: Publish to GitHub Pages

# Specifies to run this workflow whenever a push is made (commits are
# added) to the branch named `main`.
on:
  push:
    branches:
      - main

# Define a job named `build-and-publish` in your workflow.
jobs:
  build-and-publish:
    runs-on: ubuntu-latest # This job uses a GitHub-hosted runner.

    steps:
      # Checkout the source from the `main` branch.
      - uses: actions/checkout@v3

      # Set up Ruby for Jekyll.
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      # Install Jekyll and Bundler.
      - name: Install dependencies
        run: |
          cd jekyll
          gem install bundler
          bundle install

      # Build the Jekyll site with the baseurl set to 'wallace-thrasher'.
      - name: Build site
        run: |
          cd jekyll
          bundle exec jekyll build --baseurl "/wallace-thrasher"

      # Deploy to GitHub Pages.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./jekyll/_site
